# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-13 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='artist', serialize=False, to='core.Author')),
                ('nickname', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'artist',
            },
            bases=('core.author',),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='song', serialize=False, to='core.Reference')),
                ('title', models.CharField(max_length=1024)),
                ('date', models.DateField(blank=True, help_text='In cas this is a single (without album).', null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Album')),
            ],
            options={
                'db_table': 'song',
            },
            bases=('core.reference',),
        ),
    ]
